// Generated by CoffeeScript 1.6.1
(function() {
  var add_assignee_menu;

  add_assignee_menu = function() {
    var $assigneeInputs, $sidebarFilters, assignee, assignees, baseUrl, hrTemplate, input, rIssuesUrl, urlParameters, urlParts, _i, _j, _len, _len1, _results;
    if (!$('.filter-by-assignee').length) {
      assignees = [];
      $sidebarFilters = $('.issues-list-sidebar').find('ul.filter-list').first();
      $assigneeInputs = $('form.js-assignee-picker-form').first().find('input[name="assignment[assignee]"]');
      rIssuesUrl = /^(.*\/\/github.com\/.*\/issues).*?(\?.*)?/;
      urlParts = rIssuesUrl.exec(window.location.href);
      if (!urlParts) {
        return null;
      }
      baseUrl = urlParts[1];
      urlParameters = urlParts[2];
      hrTemplate = "<li>\n    <div class=\"rule\"></div>\n    <strong>Assigned To:</strong>\n</li>";
      for (_i = 0, _len = $assigneeInputs.length; _i < _len; _i++) {
        input = $assigneeInputs[_i];
        assignees.push($(input).val());
      }
      $sidebarFilters.append(hrTemplate);
      _results = [];
      for (_j = 0, _len1 = assignees.length; _j < _len1; _j++) {
        assignee = assignees[_j];
        _results.push($sidebarFilters.append("<li class=\"filter-by-assignee\">\n    <a href=\"" + baseUrl + "/assigned/" + assignee + (urlParameters || '') + "\">\n        <span class=\"name\">" + assignee + "</span>\n    </a>\n</li>"));
      }
      return _results;
    }
  };

  add_assignee_menu();

  $(document).ajaxComplete(add_assignee_menu);

}).call(this);
